services:
  - type: web
    name: haqdaari-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install && npm run backend:build
    startCommand: npm run backend:start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
    healthCheckPath: /api/audit
